BACKPORT: seccomp: add filter_count field for KernelSU
KernelSU requires struct seccomp to have atomic_t filter_count ,
but this field is missing on NON-GKI kernels.

Adding the field fixes build errors such as:
error: no member named 'filter_count' in 'struct seccomp'

Reference: tiann/KernelSU#2708

See this commit:
https://github.com/sidex15/android_kernel_lge_sm8150/commit/0edae346cc4df80ae7ef15ed204887a8f24f9480